version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
      next-react:
        patterns:
          - next
          - eslint-config-next
          - react
          - react-dom
          - '@types/react*'
      supabase:
        patterns:
          - '@supabase/*'
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
