import {
  Activity,
  Building2,
  Calendar,
  ClipboardList,
  CreditCard,
  FileText,
  Home,
  LayoutDashboard,
  LineChart,
  Mail,
  MessageSquare,
  RefreshCw,
  Settings,
  ShieldAlert,
  Users,
  UsersRound,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const navIcons: Record<string, LucideIcon> = {
  activity: Activity,
  billing: CreditCard,
  campaigns: Mail,
  customers: UsersRound,
  customersGlobal: Users,
  dashboard: LayoutDashboard,
  home: Home,
  inquiries: Mail,
  invoices: FileText,
  messages: MessageSquare,
  paymentMethods: CreditCard,
  quotes: ClipboardList,
  reports: LineChart,
  schedule: Calendar,
  settings: Settings,
  stripe: CreditCard,
  subscriptions: RefreshCw,
  tenants: Building2,
  users: Users,
  visits: Calendar,
  work: Wrench,
  audit: ShieldAlert,
};
